// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1siU5fp5w8q2mGq2mCA5rgfCitGs0vYQ',
    appId: '1:1050861697824:android:fecbf5532f19237863b545',
    messagingSenderId: '1050861697824',
    projectId: 'qm-trading-app-48318',
    storageBucket: 'qm-trading-app-48318.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn4K6c26mpmBSy6Nln9FVZWQNawUuiZJc',
    appId: '1:1050861697824:ios:59be1fca1b6ace8463b545',
    messagingSenderId: '1050861697824',
    projectId: 'qm-trading-app-48318',
    storageBucket: 'qm-trading-app-48318.appspot.com',
    androidClientId: '1050861697824-r2ep328nd60cjmtkte99769innkk7b6j.apps.googleusercontent.com',
    iosClientId: '1050861697824-3k1bm3um4lj5hj5in99tb1vtctcfislo.apps.googleusercontent.com',
    iosBundleId: 'com.nesscale.qmMlm',
  );
}
